table dim_date
	lineageTag: 4c79467a-d807-437f-95c8-4730dd095a1d

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: a475cb86-cee3-48d9-81d2-ffed998dbe9b
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column calendar_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 31142508-448f-4ef4-a777-5776c95b3b32
		summarizeBy: none
		sourceColumn: calendar_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: a8d35a7b-22cc-4acd-8c10-c08283768ce1
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 57ebdf7b-4e53-41eb-a607-f87f53ada9c2
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: ed1fb4a3-ed19-450f-843f-a3aa1902723d
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 3ce857c5-0324-45b3-8fef-ac798178e55c
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: b05e9452-7b5e-477e-9030-97f4d0b8ce2e
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column is_weekday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d7129114-98e3-40ba-9c14-f86222a8ae8d
		summarizeBy: none
		sourceColumn: is_weekday

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Ary Palacios\Desktop\portfolio-risk-analytics\data\processed\dim_date.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"date_key", Int64.Type}, {"calendar_date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"day", Int64.Type}, {"year_month", type date}, {"is_weekday", type logical}}, "es")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_ResultType = Table

